# Generated by Django 4.0.4 on 2022-05-16 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='更新时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
