# Generated by Django 4.0.4 on 2022-05-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], null=True, verbose_name='性别'),
        ),
    ]
