# Generated by Django 4.0.4 on 2022-05-17 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userinfo_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='nick_name',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='api.user'),
        ),
    ]
