# Generated by Django 4.0.4 on 2022-05-17 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_nick_name_userinfo_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('avatar', models.CharField(max_length=255, verbose_name='照片')),
                ('category', models.IntegerField(choices=[(0, '狗狗'), (1, '猫咪')], verbose_name='类别')),
                ('sub_category', models.IntegerField(verbose_name='子类别')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='api.user')),
            ],
        ),
    ]
