# Generated by Django 4.0.4 on 2022-05-24 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_user_userinfo_info_userinfo_introduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='info',
            new_name='owner',
        ),
    ]
