# Generated by Django 4.0.4 on 2022-05-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_info_userinfo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, verbose_name='照片'),
        ),
    ]
