# Generated by Django 4.0.4 on 2022-05-24 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userinfo_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetIntrinsic',
            fields=[
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='intrinsic', serialize=False, to='api.pet')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('category', models.IntegerField(choices=[(0, '狗狗'), (1, '猫咪')], verbose_name='类别')),
                ('sub_category', models.IntegerField(verbose_name='子类别')),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='sub_category',
        ),
    ]
