# Generated by Django 4.0.4 on 2022-05-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_petintrinsic_remove_pet_category_remove_pet_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petintrinsic',
            old_name='pet',
            new_name='owner',
        ),
    ]
