# Generated by Django 4.0.4 on 2022-05-24 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_pet_petintrinsic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='petintrinsic',
            name='birthday',
            field=models.DateField(default=datetime.date(2022, 5, 24), verbose_name='生日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petintrinsic',
            name='neuter',
            field=models.BooleanField(null=True, verbose_name='是否绝育'),
        ),
    ]
