# Generated by Django 4.0.4 on 2022-05-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_petintrinsic_birthday_petintrinsic_neuter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='introduction',
            field=models.CharField(blank=True, max_length=200, verbose_name='个性签名'),
        ),
    ]
