# Generated by Django 4.0.4 on 2022-06-02 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pet_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='帖子文案')),
                ('type', models.IntegerField(choices=[(0, '图文'), (1, '视频')], verbose_name='类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.user')),
                ('pets', models.ManyToManyField(related_name='posts', to='api.pet')),
            ],
            options={
                'verbose_name': '帖子',
            },
        ),
        migrations.CreateModel(
            name='PostTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='话题标题')),
                ('description', models.CharField(max_length=200, verbose_name='话题描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.user')),
                ('posts', models.ManyToManyField(related_name='topics', to='api.post')),
            ],
            options={
                'verbose_name': '主题',
            },
        ),
        migrations.CreateModel(
            name='TopicAuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '审核成功'), (1, '审核中'), (2, '审核失败')], verbose_name='审核状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditRecords', to='api.posttopic')),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500, verbose_name='七牛云Key')),
                ('type', models.IntegerField(choices=[(0, '图片'), (1, '视频')], verbose_name='类型')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='api.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post')),
            ],
            options={
                'verbose_name': '评论',
            },
        ),
    ]
