# Generated by Django 4.0.4 on 2022-06-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_post_posttopic_topicauditrecord_postmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttopic',
            name='audit_status',
            field=models.IntegerField(choices=[(0, '审核成功'), (1, '审核中'), (2, '审核失败')], default=1, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'UserRole.NORMAL'), (1, 'UserRole.OFFICIAL')], default=0, verbose_name='角色'),
        ),
    ]
