# Generated by Django 4.0.4 on 2022-06-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_postcomment_audit_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complains', to='api.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
