# Generated by Django 4.0.4 on 2022-06-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_postcomplain_options_postcomplain_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audit_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='post',
            name='audit_status',
            field=models.IntegerField(choices=[(0, '审核成功'), (1, '审核中'), (2, '审核失败')], default=1, verbose_name='审核状态'),
        ),
    ]
