# Generated by Django 4.0.4 on 2022-06-07 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0020_post_audit_description_post_audit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500, verbose_name='七牛云Key')),
                ('type', models.IntegerField(choices=[(0, '图片'), (1, '视频')], verbose_name='类型')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '图片/视频',
            },
        ),
        migrations.DeleteModel(
            name='PostMedia',
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['content_type', 'object_id'], name='api_media_content_8be83b_idx'),
        ),
    ]
