# Generated by Django 4.0.4 on 2022-06-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': '反馈'},
        ),
        migrations.AddField(
            model_name='post',
            name='collectors',
            field=models.ManyToManyField(related_name='collections', to='api.user'),
        ),
    ]
