# Generated by Django 4.0.4 on 2022-06-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_praise_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='praise',
            options={'ordering': ['pk']},
        ),
        migrations.AddConstraint(
            model_name='praise',
            constraint=models.UniqueConstraint(fields=('object_id', 'content_type', 'owner'), name='one_praise_one_target'),
        ),
    ]
