# Generated by Django 4.0.4 on 2022-06-16 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_user_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pk',), 'verbose_name': '帖子'},
        ),
    ]
