# Generated by Django 4.0.4 on 2022-06-21 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0033_user_create_time_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_status', models.IntegerField(choices=[(0, '审核成功'), (1, '审核中'), (2, '审核失败')], default=1, verbose_name='审核状态')),
                ('audit_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='审核意见')),
                ('description', models.CharField(max_length=200, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.user')),
            ],
            options={
                'verbose_name': '评论',
            },
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
