# Generated by Django 4.0.4 on 2022-06-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0034_comment_delete_postcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('latitude', models.FloatField(verbose_name='维度')),
                ('longitude', models.FloatField(verbose_name='精度')),
                ('country', models.CharField(max_length=10, verbose_name='国家')),
                ('province', models.CharField(max_length=10, verbose_name='省份')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=30, null=True, verbose_name='区县')),
                ('street', models.CharField(blank=True, max_length=30, null=True, verbose_name='街道')),
                ('down', models.CharField(blank=True, max_length=30, null=True, verbose_name='乡镇')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('ad_code', models.CharField(max_length=10, verbose_name='行政区划编码')),
                ('city_code', models.CharField(max_length=10, verbose_name='城市编码')),
                ('slang', models.CharField(blank=True, max_length=50, null=True, verbose_name='语义化描述')),
                ('poi_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='poi名称')),
                ('poi_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='poi地址')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
