# Generated by Django 4.0.4 on 2022-06-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_down_address_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postNotices',
            field=models.ManyToManyField(related_name='notice_users', to='api.post'),
        ),
    ]
