# Generated by Django 4.0.4 on 2022-06-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_userinfo_center_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petintrinsic',
            name='birthday',
            field=models.DateTimeField(verbose_name='生日'),
        ),
    ]
