# Generated by Django 4.0.4 on 2022-07-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_petintrinsic_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, null=True, verbose_name='密码'),
        ),
    ]
